// <auto-generated />
namespace Classifieds.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class other : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(other));
        
        string IMigrationMetadata.Id
        {
            get { return "201308270340549_other"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
