// <auto-generated />
namespace Classifieds.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class StringValue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StringValue));
        
        string IMigrationMetadata.Id
        {
            get { return "201311240056141_StringValue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
