// <auto-generated />
namespace Classifieds.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class AddingParentsIDS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingParentsIDS));
        
        string IMigrationMetadata.Id
        {
            get { return "201401212213527_AddingParentsIDS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
